const PDFDocument = require("pdfkit");
const db = require("../db");

// ===============================
// Download Individual Feedback PDF
// ===============================
exports.downloadFeedbackPDF = async (req, res) => {

    try {

        const feedbackId = req.params.id;

        const [rows] = await db.query(
            `SELECT *
             FROM feedback
             WHERE feedback_id = ?`,
            [feedbackId]
        );

        if (rows.length === 0) {

            return res.status(404).json({
                success: false,
                message: "Feedback not found"
            });

        }

        const f = rows[0];

        res.setHeader(
            "Content-Type",
            "application/pdf"
        );

        res.setHeader(
            "Content-Disposition",
            `attachment; filename=TYLT_Feedback_${f.booking_id}.pdf`
        );

        const doc = new PDFDocument({
            margin: 40,
            size: "A4"
        });

        doc.pipe(res);

        //----------------------------------
        // Header
        //----------------------------------

        doc
            .fontSize(24)
            .fillColor("#003366")
            .text("TYLT Mobility", {
                align: "center"
            });

        doc
            .moveDown(0.2)
            .fontSize(16)
            .fillColor("black")
            .text("Customer Feedback Report", {
                align: "center"
            });

        doc.moveDown();

        //----------------------------------
        // Booking Information
        //----------------------------------

        doc
            .fontSize(14)
            .fillColor("#0d6efd")
            .text("Trip Details");

        doc.moveDown(0.5);

        addRow(doc, "Booking ID", f.booking_id);
        addRow(doc, "Customer", f.customer_name);
        addRow(doc, "Company", f.company_name);
        addRow(doc, "Driver", f.driver_name);
        addRow(doc, "Vehicle", f.vehicle_number);
        addRow(doc, "Trip Date", formatDate(f.trip_date));

        doc.moveDown();

        //----------------------------------
        // Ratings
        //----------------------------------

        doc
            .fontSize(14)
            .fillColor("#0d6efd")
            .text("Ratings");

        doc.moveDown(0.5);

        addRow(doc, "Overall Rating", stars(f.overall_rating));
        addRow(doc, "Driver Rating", stars(f.driver_rating));
        addRow(doc, "Cleanliness", stars(f.cleanliness_rating));
        addRow(doc, "Punctuality", stars(f.punctuality_rating));

        doc.moveDown();

        //----------------------------------
        // Recommendation
        //----------------------------------

        doc
            .fontSize(14)
            .fillColor("#0d6efd")
            .text("Recommendation");

        doc.moveDown(0.5);

        addRow(doc, "Would Recommend", f.recommendation);

        doc.moveDown();

        //----------------------------------
        // Comments
        //----------------------------------

        doc
            .fontSize(14)
            .fillColor("#0d6efd")
            .text("Customer Comments");

        doc.moveDown(0.5);

        doc
            .fontSize(12)
            .fillColor("black")
            .text(
                f.comments || "No comments provided.",
                {
                    width: 500,
                    align: "left"
                }
            );

        doc.moveDown(2);

        //----------------------------------
        // Footer
        //----------------------------------

        doc
            .fontSize(10)
            .fillColor("gray")
            .text(
                "Generated by TYLT Mobility Feedback System",
                {
                    align: "center"
                }
            );

        doc.end();

    }

    catch (err) {

        console.error(err);

        res.status(500).json({
            success: false,
            message: "Unable to generate PDF."
        });

    }

};

function addRow(doc, label, value) {

    doc
        .font("Helvetica-Bold")
        .fillColor("black")
        .text(label + " :", {
            continued: true,
            width: 180
        });

    doc
        .font("Helvetica")
        .text(" " + (value || "-"));

}

function stars(value) {

    return "⭐".repeat(Number(value));

}

function formatDate(date) {

    return new Date(date).toLocaleDateString();

}